version: '3'

services:

  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx/
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    networks:
      - net 
    restart: always


  wordpress:
    container_name: wordpress
    build: ./srcs/requirements/wordpress/
    volumes:
      - wp:/var/www/html
    networks:
      - net 
    restart: always


  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb/
    volumes:
      - wp:/var/www/html
    networks:
      - net 
    restart: always

# Partages de fichier entre les containers
volumes:
  wp:

# Permet aux conteneurs de communiquer entre eux sur le réseau avec "driver: bridge"
networks:
  net:
    name: net
    driver: bridge