version: '3'

services:
  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx/
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    networks:
      - net 
    restart: always

  wordpress:
    container_name: wordpress
    build: ./srcs/requirements/wordpress/
    volumes:
      - wp:/var/www/html
    networks:
      - net 
    restart: always

  # db:
  #   build: ./requirements/nginx/Dockerfile
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=your_password
  #     - MYSQL_DATABASE=your_database
  #     - MYSQL_USER=your_user
  #     - MYSQL_PASSWORD=your_password
  #   restart: always

volumes:
  wp:

networks:
  net:
    name: net
    driver: bridge