version: '3'

services:

  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx/
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    networks:
      - net 
    restart: always

  wordpress:
    container_name: wordpress
    build: ./srcs/requirements/wordpress/
    ports:
      - 9000:9000
    volumes:
      - wp:/var/www/html
    networks:
      - net 
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb/
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - net 
    restart: always
    env_file:
      - .env


# Partages de fichier entre les containers
volumes: 
  wp:
    driver: local
    name: wp
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/luserbu/data/wordpress"
  db_data:
    driver: local
    name: db_data
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/luserbu/data/mariadb"

# Permet aux conteneurs de communiquer entre eux sur le réseau avec "driver: bridge"
networks:
  net:
    name: net
    driver: bridge