version: "3.5"

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    networks:
      - net
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - net
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - net
    env_file:
      - .env
    restart: always


# Partages de fichier entre les containers
volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/luserbu/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/luserbu/data/mariadb

# Permet aux conteneurs de communiquer entre eux sur le meme réseau avec "driver: bridge"
networks:
  net:
    name: netception
    driver: bridge